### ISSUE TITLE
リンク切れ

### ISSUE THREAD

**Issue by OzoneAsai** [ikegami-yukino/dataset-list#2]
`https://github.com/ikegami-yukino/dataset-list/blob/master/free_text_corpus.md`の、
`https://nknet.ninjal.ac.jp/nuc/templates/nuc.html`を次のいずれかに置き換えてください。

`https://www2.ninjal.ac.jp/conversation/nuc.html`
`https://mmsrv.ninjal.ac.jp/nucc/` 　←推奨

**Comment by OzoneAsai** [comment]
また、
![image](https://github.com/ikegami-yukino/dataset-list/assets/56304837/2f3b3644-0262-4370-aeb6-e70f4f2c8bb7)

**Comment by ikegami-yukino** [comment]
@OzoneAsai 
ありがとうございます！修正しました！
